# Generated by Django 5.2.3 on 2025-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_alter_playhistory_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(choices=[('beginner', '初心者向け'), ('intermediate', '中級者向け'), ('advanced', '上級者向け'), ('expert', 'エキスパート')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='scenario',
            name='estimated_duration',
            field=models.CharField(choices=[('short', '短編（〜3時間）'), ('medium', '中編（3〜6時間）'), ('long', '長編（6時間〜）'), ('campaign', 'キャンペーン')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='scenario',
            name='recommended_players',
            field=models.CharField(blank=True, help_text='推奨人数（例: 3-4人）', max_length=50),
        ),
        migrations.AddField(
            model_name='scenario',
            name='url',
            field=models.URLField(blank=True, help_text='参照URL'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='推定プレイ時間（分）', null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='game_system',
            field=models.CharField(choices=[('coc', 'クトゥルフ神話TRPG'), ('dnd', 'D&D'), ('sw', 'ソード・ワールド'), ('insane', 'インセイン'), ('other', 'その他')], default='coc', max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='player_count',
            field=models.PositiveIntegerField(blank=True, help_text='推奨プレイヤー数', null=True),
        ),
    ]
