# Generated by Django 4.2.27 on 2026-01-12 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0004_scenario_recommended_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='シナリオに関連する画像', upload_to='scenario_images/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, help_text='画像のタイトル', max_length=200)),
                ('description', models.TextField(blank=True, help_text='画像の説明')),
                ('order', models.PositiveIntegerField(default=0, help_text='表示順序')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scenarios.scenario')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scenario_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['scenario', 'order'], name='scenarios_s_scenari_b1ca29_idx')],
            },
        ),
    ]
