# Generated by Django 5.2.15 on 2026-06-27 00:43

import django.db.models.deletion
import django.utils.timezone
import re
from django.db import migrations, models


def split_skill_text(value):
    if not value:
        return []
    normalized = re.sub(r'[、，\n\r;；/／]+', ',', value)
    return [item.strip() for item in normalized.split(',') if item.strip()]


def migrate_structured_scenario_data(apps, schema_editor):
    Scenario = apps.get_model('scenarios', 'Scenario')
    ScenarioHandout = apps.get_model('scenarios', 'ScenarioHandout')
    ScenarioRecommendedSkill = apps.get_model('scenarios', 'ScenarioRecommendedSkill')
    ScenarioHandoutRecommendedSkill = apps.get_model('scenarios', 'ScenarioHandoutRecommendedSkill')

    for scenario in Scenario.objects.all().iterator():
        order = 1
        for name in split_skill_text(scenario.recommended_skills):
            ScenarioRecommendedSkill.objects.create(
                scenario=scenario,
                name=name,
                level='recommended',
                order=order,
            )
            order += 1
        for name in split_skill_text(scenario.semi_recommended_skills):
            ScenarioRecommendedSkill.objects.create(
                scenario=scenario,
                name=name,
                level='semi_recommended',
                order=order,
            )
            order += 1

    for handout in ScenarioHandout.objects.all().iterator():
        updates = []
        if not handout.name:
            handout.name = handout.title
            updates.append('name')
        if not handout.code and handout.handout_number:
            handout.code = f'HO{handout.handout_number}'
            updates.append('code')
        if not handout.order:
            handout.order = handout.handout_number or handout.id
            updates.append('order')
        if updates:
            handout.save(update_fields=updates)

        for order, name in enumerate(split_skill_text(handout.recommended_skills), start=1):
            ScenarioHandoutRecommendedSkill.objects.create(
                handout=handout,
                name=name,
                level='recommended',
                order=order,
            )


def reverse_structured_scenario_data(apps, schema_editor):
    apps.get_model('scenarios', 'ScenarioRecommendedSkill').objects.all().delete()
    apps.get_model('scenarios', 'ScenarioHandoutRecommendedSkill').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0007_scenario_planning_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioHandoutRecommendedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('semi_recommended', 'Semi recommended'), ('optional', 'Optional')], default='recommended', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRecommendedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('semi_recommended', 'Semi recommended'), ('optional', 'Optional')], default='recommended', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='scenariohandout',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='scenariohandout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scenariohandout',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='scenariohandout',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scenariohandout',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenariohandout',
            name='handout_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='scenariohandout',
            index=models.Index(fields=['scenario', 'order'], name='scenarios_s_scenari_b20106_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariohandout',
            index=models.Index(fields=['scenario', 'code'], name='scenarios_s_scenari_34a403_idx'),
        ),
        migrations.AddField(
            model_name='scenariohandoutrecommendedskill',
            name='handout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_skill_items', to='scenarios.scenariohandout'),
        ),
        migrations.AddField(
            model_name='scenariorecommendedskill',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_skill_items', to='scenarios.scenario'),
        ),
        migrations.AddIndex(
            model_name='scenariohandoutrecommendedskill',
            index=models.Index(fields=['handout', 'order'], name='scenarios_s_handout_04f5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariorecommendedskill',
            index=models.Index(fields=['scenario', 'order'], name='scenarios_s_scenari_050086_idx'),
        ),
        migrations.RunPython(
            migrate_structured_scenario_data,
            reverse_structured_scenario_data,
        ),
    ]
