# Generated by Django 5.2.15 on 2026-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0008_scenariohandoutrecommendedskill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("group", "Group"), ("link", "Link"), ("public", "Public")],
                default="public",
                max_length=10,
            ),
        ),
    ]
