# Generated by Django 5.2.3 on 2025-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_charactersheet_characterequipment_charactersheet6th_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskill',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='ボーナスポイント'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='category',
            field=models.CharField(choices=[('探索系', '探索系'), ('対人系', '対人系'), ('戦闘系', '戦闘系'), ('知識系', '知識系'), ('技術系', '技術系'), ('行動系', '行動系'), ('言語系', '言語系'), ('特殊・その他', '特殊・その他')], default='特殊・その他', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
