# Generated by Django 5.2.3 on 2025-06-16 13:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_charactersheet_cocoholia_character_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDiceRollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100, verbose_name='設定名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト設定')),
                ('str_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='STRダイス数')),
                ('str_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='STRダイス面数')),
                ('str_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='STRボーナス')),
                ('con_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='CONダイス数')),
                ('con_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='CONダイス面数')),
                ('con_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='CONボーナス')),
                ('pow_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='POWダイス数')),
                ('pow_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='POWダイス面数')),
                ('pow_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='POWボーナス')),
                ('dex_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='DEXダイス数')),
                ('dex_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='DEXダイス面数')),
                ('dex_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='DEXボーナス')),
                ('app_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='APPダイス数')),
                ('app_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='APPダイス面数')),
                ('app_bonus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='APPボーナス')),
                ('siz_dice_count', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='SIZダイス数')),
                ('siz_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='SIZダイス面数')),
                ('siz_bonus', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='SIZボーナス')),
                ('int_dice_count', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='INTダイス数')),
                ('int_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='INTダイス面数')),
                ('int_bonus', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='INTボーナス')),
                ('edu_dice_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='EDUダイス数')),
                ('edu_dice_sides', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='EDUダイス面数')),
                ('edu_bonus', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='EDUボーナス')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice_roll_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ダイスロール設定',
                'verbose_name_plural': 'ダイスロール設定',
                'ordering': ['-is_default', 'setting_name'],
                'unique_together': {('user', 'setting_name')},
            },
        ),
    ]
