# Generated by Django 5.2.3 on 2025-06-19 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_fix_6th_edition_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_description', models.TextField(blank=True, max_length=1000, verbose_name='容姿・特徴')),
                ('beliefs_ideology', models.TextField(blank=True, max_length=1000, verbose_name='信念・信条')),
                ('significant_people', models.TextField(blank=True, max_length=1000, verbose_name='大切な人物')),
                ('meaningful_locations', models.TextField(blank=True, max_length=1000, verbose_name='意味のある場所')),
                ('treasured_possessions', models.TextField(blank=True, max_length=1000, verbose_name='愛用の品')),
                ('traits_mannerisms', models.TextField(blank=True, max_length=1000, verbose_name='特徴・癖')),
                ('personal_history', models.TextField(blank=True, max_length=2000, verbose_name='生い立ち')),
                ('important_events', models.TextField(blank=True, max_length=2000, verbose_name='重要な出来事')),
                ('scars_injuries', models.TextField(blank=True, max_length=1000, verbose_name='傷・傷跡')),
                ('phobias_manias', models.TextField(blank=True, max_length=1000, verbose_name='恐怖症・マニア')),
                ('fellow_investigators', models.TextField(blank=True, max_length=2000, verbose_name='仲間の探索者')),
                ('notes_memo', models.TextField(blank=True, max_length=3000, verbose_name='メモ欄')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_info', to='accounts.charactersheet')),
            ],
            options={
                'verbose_name': 'キャラクター背景情報',
                'verbose_name_plural': 'キャラクター背景情報',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='セッション日付')),
                ('scenario_name', models.CharField(max_length=200, verbose_name='シナリオ名')),
                ('gm_name', models.CharField(blank=True, max_length=100, verbose_name='GM名')),
                ('sanity_gained', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='正気度獲得')),
                ('sanity_lost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='正気度喪失')),
                ('experience_gained', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='獲得経験値')),
                ('special_rewards', models.TextField(blank=True, max_length=1000, verbose_name='特別報酬')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='セッション備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='accounts.charactersheet')),
            ],
            options={
                'verbose_name': '成長記録',
                'verbose_name_plural': '成長記録',
                'ordering': ['-session_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='技能名')),
                ('had_experience_check', models.BooleanField(default=False, verbose_name='経験チェック有無')),
                ('growth_roll_result', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='成長ロール結果')),
                ('old_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='成長前技能値')),
                ('new_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='成長後技能値')),
                ('growth_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='成長量')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='成長備考')),
                ('growth_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_growths', to='accounts.growthrecord')),
            ],
            options={
                'verbose_name': '技能成長記録',
                'verbose_name_plural': '技能成長記録',
                'ordering': ['skill_name'],
            },
        ),
    ]
