# Generated by Django 5.2.3 on 2025-06-21 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_background_and_growth_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='app_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='外見(APP)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='con_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='体力(CON)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='dex_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='敏捷性(DEX)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='edu_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='教育(EDU)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='int_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='知識(INT)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='pow_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='意志力(POW)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='siz_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='体格(SIZ)'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='str_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(90)], verbose_name='筋力(STR)'),
        ),
    ]
