# Generated by Django 5.2.3 on 2025-06-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_charactersheet_app_value_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactersheet',
            unique_together=set(),
        ),
    ]
