# Generated by Django 5.2.3 on 2025-06-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_unique_constraint_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='character_images/%Y/%m/%d/', verbose_name='画像')),
                ('is_main', models.BooleanField(default=False, verbose_name='メイン画像')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('character_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.charactersheet', verbose_name='キャラクターシート')),
            ],
            options={
                'verbose_name': 'キャラクター画像',
                'verbose_name_plural': 'キャラクター画像',
                'ordering': ['order', 'uploaded_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('character_sheet',), name='unique_main_image_per_character')],
            },
        ),
    ]
