# Generated by Django 5.2.3 on 2025-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_characterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='status',
            field=models.CharField(choices=[('alive', '生存'), ('dead', '死亡'), ('insane', '発狂'), ('injured', '重傷'), ('missing', '行方不明'), ('retired', '引退')], default='alive', max_length=10, verbose_name='状態'),
        ),
    ]
