# Generated by Django 5.2.3 on 2025-06-23 12:48

from django.db import migrations, models

import accounts.character_models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_charactersheet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterimage",
            name="image",
            field=models.ImageField(upload_to=accounts.character_models.CharacterImage.upload_to, verbose_name="画像"),
        ),
    ]
