# Generated by Django 5.2.3 on 2025-06-23 12:48

import os
import uuid

from django.db import migrations, models
from django.utils import timezone


def upload_to(instance, filename):
    """Keep this historical migration independent from runtime models."""
    base_name = os.path.basename(filename)
    unique_filename = f"{instance.character_sheet_id}_{uuid.uuid4().hex[:8]}_{base_name}"
    return f"character_images/{timezone.now().year}/{timezone.now().month:02d}/{unique_filename}"


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_charactersheet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterimage",
            name="image",
            field=models.ImageField(upload_to=upload_to, verbose_name="画像"),
        ),
    ]
