# Generated by Django 5.2.3 on 2025-06-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_characterimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開設定'),
        ),
    ]
