# Generated by Django 4.2.27 on 2025-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_skillgrowthrecord_growth_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='recommended_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='推奨技能'),
        ),
    ]
