# Generated by Django 4.2.27 on 2025-12-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_charactersheet_recommended_skills'),
        ('scenarios', '0004_scenario_recommended_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='source_scenario',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='linked_characters',
                to='scenarios.scenario',
                verbose_name='元シナリオ'
            ),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='source_scenario_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='元シナリオ名'),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='source_scenario_game_system',
            field=models.CharField(blank=True, max_length=10, verbose_name='元シナリオシステム'),
        ),
    ]
