# Generated by Django 4.2.27 on 2026-01-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_charactersheet_occupation_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='edition',
            field=models.CharField(choices=[('6th', '6版'), ('7th', '7版')], max_length=3),
        ),
    ]
