# Generated by Django 4.2.27 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_charactersheet_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='課金ユーザ（高権限ユーザ）'),
        ),
    ]
