# Generated by Django 4.2.27 on 2026-06-11 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_groupdiscordsettings_discorddelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_group_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_group_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_links", to="accounts.group"
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="incoming_links", to="accounts.group"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupLinkShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("session", "Session"),
                            ("date_poll", "Date poll"),
                            ("scenario", "Scenario"),
                            ("session_template", "Session template"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_group_link_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="accounts.grouplink"
                    ),
                ),
                (
                    "owner_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_resource_shares",
                        to="accounts.group",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="grouplinkshare",
            constraint=models.UniqueConstraint(
                fields=("link", "owner_group", "resource_type", "object_id"), name="unique_group_link_resource_share"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplink",
            constraint=models.UniqueConstraint(
                fields=("source_group", "target_group"), name="unique_directed_group_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="grouplink",
            constraint=models.CheckConstraint(
                check=models.Q(("source_group", models.F("target_group")), _negated=True),
                name="group_link_groups_must_differ",
            ),
        ),
    ]
