# Generated by Django 5.2.15 on 2026-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_alter_premiumauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripewebhookevent",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stripewebhookevent",
            name="processing_status",
            field=models.CharField(
                choices=[("processing", "Processing"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                db_index=True,
                default="succeeded",
                max_length=32,
            ),
        ),
    ]
