# Generated by Codex on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_stripewebhookevent_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumaccesscode",
            name="campaign_name",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
