# Generated by Django 5.2.15 on 2026-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_premiumaccesscode_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='billing_interval',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
