# Generated by Codex on 2026-06-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_character_sheet_access_scope"),
        ("accounts", "0044_premium_subscription_billing_plan_fields"),
    ]

    operations = []
