# Generated by Django 5.2.15 on 2026-06-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_merge_character_access_and_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouplinkshare",
            name="resource_type",
            field=models.CharField(
                choices=[("session", "Session"), ("date_poll", "Date poll"), ("scenario", "Scenario")], max_length=32
            ),
        ),
    ]
