# Generated by Django 5.2.15 on 2026-06-27 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_grouplinkshare_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='access_scope',
            field=models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('link', 'Link'), ('public', 'Public')], default='group', max_length=10, verbose_name='Access scope'),
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('character', 'Character'), ('session', 'Session'), ('scenario', 'Scenario'), ('profile_stats', 'Profile stats')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('view_level', models.CharField(choices=[('summary', 'Summary'), ('standard', 'Standard'), ('full', 'Full')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'object_id'], name='accounts_sh_resourc_7fad27_idx'), models.Index(fields=['created_by', 'created_at'], name='accounts_sh_created_377c22_idx')],
            },
        ),
    ]
