# Generated by Django 5.2 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0052_charactersheet_age_nullable")]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="name_kana",
            field=models.CharField(blank=True, max_length=100, verbose_name="Character name reading"),
        ),
    ]
