# Generated by Django 5.2.15 on 2026-07-15 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


SYSTEM_DATA_FIELDS = (
    "name_kana", "name", "player_name", "status", "age", "gender", "occupation",
    "birthplace", "residence", "recommended_skills", "occupation_skills",
    "source_scenario_id", "source_scenario_title", "source_scenario_game_system",
    "str_value", "con_value", "pow_value", "dex_value", "app_value", "siz_value",
    "int_value", "edu_value", "occupation_multiplier", "occupation_point_method",
    "hit_points_max", "hit_points_current", "magic_points_max", "magic_points_current",
    "sanity_starting", "sanity_max", "sanity_current", "notes", "secret_ho_info",
)


def copy_character_data_to_edition_tables(apps, schema_editor):
    CharacterSheet = apps.get_model("accounts", "CharacterSheet")
    CharacterSheet6th = apps.get_model("accounts", "CharacterSheet6th")
    CharacterSheet7th = apps.get_model("accounts", "CharacterSheet7th")

    for character in CharacterSheet.objects.all().iterator():
        values = {field: getattr(character, field) for field in SYSTEM_DATA_FIELDS}
        if character.edition == "6th":
            CharacterSheet6th.objects.update_or_create(character_sheet_id=character.id, defaults=values)
        elif character.edition == "7th":
            CharacterSheet7th.objects.update_or_create(character_sheet_id=character.id, defaults=values)


def noop_reverse(apps, schema_editor):
    # The parent data is deliberately retained until all reads use edition data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_remove_cross_edition_basic_skills"),
        ("scenarios", "0010_scenario_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet6th",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="app_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="birthplace",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="con_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="dex_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="edu_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="hit_points_current",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="hit_points_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="int_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="magic_points_current",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="magic_points_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="name_kana",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="occupation_multiplier",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="occupation_point_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="occupation_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="player_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="pow_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="recommended_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="residence",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="sanity_current",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="sanity_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="sanity_starting",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="secret_ho_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="siz_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="source_scenario",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="scenarios.scenario"
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="source_scenario_game_system",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="source_scenario_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="status",
            field=models.CharField(
                choices=[
                    ("alive", "生存"),
                    ("dead", "死亡"),
                    ("insane", "発狂"),
                    ("injured", "重傷"),
                    ("missing", "行方不明"),
                    ("retired", "引退"),
                ],
                default="alive",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="str_value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)],
            ),
        ),
        migrations.CreateModel(
            name="CharacterSheet7th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_kana", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("player_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("alive", "生存"),
                            ("dead", "死亡"),
                            ("insane", "発狂"),
                            ("injured", "重傷"),
                            ("missing", "行方不明"),
                            ("retired", "引退"),
                        ],
                        default="alive",
                        max_length=10,
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("birthplace", models.CharField(blank=True, max_length=100)),
                ("residence", models.CharField(blank=True, max_length=100)),
                ("recommended_skills", models.JSONField(blank=True, default=list)),
                ("occupation_skills", models.JSONField(blank=True, default=list)),
                ("source_scenario_title", models.CharField(blank=True, max_length=200)),
                ("source_scenario_game_system", models.CharField(blank=True, max_length=10)),
                (
                    "str_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "con_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "pow_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "dex_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "app_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "siz_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "int_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "edu_value",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("occupation_multiplier", models.IntegerField(default=20)),
                ("occupation_point_method", models.CharField(blank=True, default="", max_length=20)),
                ("hit_points_max", models.IntegerField(blank=True, null=True)),
                ("hit_points_current", models.IntegerField(blank=True, null=True)),
                ("magic_points_max", models.IntegerField(blank=True, null=True)),
                ("magic_points_current", models.IntegerField(blank=True, null=True)),
                ("sanity_starting", models.IntegerField(blank=True, null=True)),
                ("sanity_max", models.IntegerField(blank=True, null=True)),
                ("sanity_current", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("secret_ho_info", models.TextField(blank=True, default="")),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seventh_edition_data",
                        to="accounts.charactersheet",
                    ),
                ),
                (
                    "source_scenario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="scenarios.scenario"
                    ),
                ),
            ],
            options={
                "verbose_name": "7版キャラクターシートデータ",
                "verbose_name_plural": "7版キャラクターシートデータ",
            },
        ),
        migrations.RunPython(copy_character_data_to_edition_tables, noop_reverse),
    ]
