# Generated by Django 5.2.15 on 2026-07-15 13:30

import django.db.models.deletion
from django.db import migrations, models


def copy_related_data_to_edition_tables(apps, schema_editor):
    CharacterSheet6th = apps.get_model("accounts", "CharacterSheet6th")
    CharacterSheet7th = apps.get_model("accounts", "CharacterSheet7th")
    CharacterSkill = apps.get_model("accounts", "CharacterSkill")
    CharacterSkill6th = apps.get_model("accounts", "CharacterSkill6th")
    CharacterSkill7th = apps.get_model("accounts", "CharacterSkill7th")
    CharacterEquipment = apps.get_model("accounts", "CharacterEquipment")
    CharacterEquipment6th = apps.get_model("accounts", "CharacterEquipment6th")
    CharacterEquipment7th = apps.get_model("accounts", "CharacterEquipment7th")
    CharacterImage = apps.get_model("accounts", "CharacterImage")
    CharacterImage6th = apps.get_model("accounts", "CharacterImage6th")
    CharacterImage7th = apps.get_model("accounts", "CharacterImage7th")

    skill_fields = (
        "skill_name", "category", "base_value", "occupation_points", "interest_points",
        "bonus_points", "other_points", "current_value", "notes",
    )
    equipment_fields = (
        "item_type", "name", "skill_name", "damage", "base_range", "attacks_per_round",
        "ammo", "malfunction_number", "armor_points", "description", "quantity", "weight",
    )

    for skill in CharacterSkill.objects.select_related("character_sheet").iterator():
        if skill.character_sheet.edition == "6th":
            target_sheet = CharacterSheet6th.objects.get(character_sheet_id=skill.character_sheet_id)
            target_model = CharacterSkill6th
        elif skill.character_sheet.edition == "7th":
            target_sheet = CharacterSheet7th.objects.get(character_sheet_id=skill.character_sheet_id)
            target_model = CharacterSkill7th
        else:
            continue
        values = {field: getattr(skill, field) for field in skill_fields}
        values["character_sheet"] = target_sheet
        target_model.objects.update_or_create(legacy_skill_id=skill.id, defaults=values)

    for equipment in CharacterEquipment.objects.select_related("character_sheet").iterator():
        if equipment.character_sheet.edition == "6th":
            target_sheet = CharacterSheet6th.objects.get(character_sheet_id=equipment.character_sheet_id)
            target_model = CharacterEquipment6th
        elif equipment.character_sheet.edition == "7th":
            target_sheet = CharacterSheet7th.objects.get(character_sheet_id=equipment.character_sheet_id)
            target_model = CharacterEquipment7th
        else:
            continue
        values = {field: getattr(equipment, field) for field in equipment_fields}
        values["character_sheet"] = target_sheet
        target_model.objects.update_or_create(legacy_equipment_id=equipment.id, defaults=values)

    for image in CharacterImage.objects.select_related("character_sheet").iterator():
        if image.character_sheet.edition == "6th":
            target_sheet = CharacterSheet6th.objects.get(character_sheet_id=image.character_sheet_id)
            target_model = CharacterImage6th
        elif image.character_sheet.edition == "7th":
            target_sheet = CharacterSheet7th.objects.get(character_sheet_id=image.character_sheet_id)
            target_model = CharacterImage7th
        else:
            continue
        target_model.objects.update_or_create(
            legacy_image_id=image.id,
            defaults={
                "character_sheet": target_sheet,
                "image": image.image.name,
                "is_main": image.is_main,
                "order": image.order,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_add_edition_system_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterEquipment6th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_equipment_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("item_type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("skill_name", models.CharField(blank=True, max_length=100)),
                ("damage", models.CharField(blank=True, max_length=20)),
                ("base_range", models.CharField(blank=True, max_length=20)),
                ("attacks_per_round", models.IntegerField(blank=True, null=True)),
                ("ammo", models.IntegerField(blank=True, null=True)),
                ("malfunction_number", models.IntegerField(blank=True, null=True)),
                ("armor_points", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="accounts.charactersheet6th",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterEquipment7th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_equipment_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("item_type", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("skill_name", models.CharField(blank=True, max_length=100)),
                ("damage", models.CharField(blank=True, max_length=20)),
                ("base_range", models.CharField(blank=True, max_length=20)),
                ("attacks_per_round", models.IntegerField(blank=True, null=True)),
                ("ammo", models.IntegerField(blank=True, null=True)),
                ("malfunction_number", models.IntegerField(blank=True, null=True)),
                ("armor_points", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField(default=1)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="accounts.charactersheet7th",
                    ),
                ),
            ],
            options={
                "ordering": ["item_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterImage6th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_image_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("image", models.ImageField(upload_to="character_images/")),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="accounts.charactersheet6th",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)), fields=("character_sheet",), name="unique_main_6th_image"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterImage7th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_image_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("image", models.ImageField(upload_to="character_images/")),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="accounts.charactersheet7th",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)), fields=("character_sheet",), name="unique_main_7th_image"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill6th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_skill_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("skill_name", models.CharField(max_length=100)),
                ("category", models.CharField(default="その他・独自", max_length=20)),
                ("base_value", models.IntegerField(default=0)),
                ("occupation_points", models.IntegerField(default=0)),
                ("interest_points", models.IntegerField(default=0)),
                ("bonus_points", models.IntegerField(default=0)),
                ("other_points", models.IntegerField(default=0)),
                ("current_value", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="accounts.charactersheet6th",
                    ),
                ),
            ],
            options={
                "ordering": ["skill_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("character_sheet", "skill_name"), name="unique_6th_skill_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill7th",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("legacy_skill_id", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("skill_name", models.CharField(max_length=100)),
                ("category", models.CharField(default="その他・独自", max_length=20)),
                ("base_value", models.IntegerField(default=0)),
                ("occupation_points", models.IntegerField(default=0)),
                ("interest_points", models.IntegerField(default=0)),
                ("bonus_points", models.IntegerField(default=0)),
                ("other_points", models.IntegerField(default=0)),
                ("current_value", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="accounts.charactersheet7th",
                    ),
                ),
            ],
            options={
                "ordering": ["skill_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("character_sheet", "skill_name"), name="unique_7th_skill_name")
                ],
            },
        ),
        migrations.RunPython(copy_related_data_to_edition_tables, noop_reverse),
    ]
