# Generated by Django 5.2.15 on 2026-07-15 20:39

import django.db.models.deletion
from django.db import migrations, models


def move_registry_metadata(apps, schema_editor):
    CharacterSheet = apps.get_model("accounts", "CharacterSheet")
    CharacterSheet6th = apps.get_model("accounts", "CharacterSheet6th")
    CharacterSheet7th = apps.get_model("accounts", "CharacterSheet7th")

    for sheet in CharacterSheet.objects.all().iterator():
        detail_model = CharacterSheet6th if sheet.edition == "6th" else CharacterSheet7th
        try:
            detail = detail_model.objects.get(character_sheet_id=sheet.id)
        except detail_model.DoesNotExist:
            continue
        detail.character_image = sheet.character_image.name if sheet.character_image else ""
        detail.is_active = sheet.is_active
        detail.session_count = sheet.session_count
        detail.ccfolia_sync_enabled = sheet.ccfolia_sync_enabled
        detail.ccfolia_character_id = sheet.ccfolia_character_id
        detail.version = sheet.version
        detail.version_note = sheet.version_note
        if sheet.parent_sheet_id:
            try:
                detail.parent_data = detail_model.objects.get(character_sheet_id=sheet.parent_sheet_id)
            except detail_model.DoesNotExist:
                detail.parent_data = None
        detail.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_add_edition_related_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet6th",
            name="ccfolia_character_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="ccfolia_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="character_image",
            field=models.ImageField(blank=True, upload_to="character_sheets/"),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="parent_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="accounts.charactersheet6th",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="session_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet6th",
            name="version_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="ccfolia_character_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="ccfolia_sync_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="character_image",
            field=models.ImageField(blank=True, upload_to="character_sheets/"),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="parent_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="accounts.charactersheet7th",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="session_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="charactersheet7th",
            name="version_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RunPython(move_registry_metadata, noop_reverse),
    ]
