# Generated by Django 5.2.15 on 2026-07-20 03:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_charactersheet7th_luck_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundRemovalJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("source_image", models.ImageField(blank=True, upload_to="background_removal/input/")),
                ("result_image", models.ImageField(blank=True, upload_to="background_removal/output/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("task_arn", models.CharField(blank=True, max_length=512)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_removal_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
