# Generated by Django 5.2.15 on 2026-08-13 23:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_mutual_friendships(apps, schema_editor):
    Friend = apps.get_model("accounts", "Friend")
    Friend.objects.filter(user_id=models.F("friend_id")).delete()
    existing_pairs = list(Friend.objects.values_list("user_id", "friend_id"))
    for user_id, friend_id in existing_pairs:
        Friend.objects.get_or_create(user_id=friend_id, friend_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_normalize_fist_skill_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pair_key", models.CharField(db_index=True, editable=False, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("accepted", "承認済み"),
                            ("declined", "拒否"),
                            ("cancelled", "取消"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounts_friend_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(backfill_mutual_friendships, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.CheckConstraint(
                condition=models.Q(("user", models.F("friend")), _negated=True), name="friend_users_must_differ"
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("sender", models.F("recipient")), _negated=True),
                name="friend_request_users_must_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("pair_key",),
                name="unique_pending_friend_request_pair",
            ),
        ),
    ]
