# Generated by Django 5.2.15 on 2026-09-13 10:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_preserve_character_descendants"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeBillingRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "operation",
                    models.CharField(choices=[("customer", "顧客作成"), ("checkout", "購入画面作成")], max_length=16),
                ),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("parameters", models.JSONField(default=dict)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.premiumsubscription"),
                ),
            ],
            options={
                "verbose_name": "Stripe作成リクエスト",
                "constraints": [
                    models.UniqueConstraint(fields=("subscription", "operation"), name="unique_stripe_billing_request")
                ],
            },
        ),
    ]
