# Generated by Django 5.2.15 on 2026-09-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_stripe_billing_requests"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeInvoiceState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("payment_failed", models.BooleanField(default=False)),
                ("last_event_id", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.premiumsubscription"),
                ),
            ],
            options={
                "verbose_name": "Stripe請求状態",
            },
        ),
    ]
