# Generated by Django 5.2.15 on 2026-09-19 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0066_stripe_invoice_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingEmailDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "送信待ち"), ("sent", "送信済み"), ("canceled", "送信不要")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_delivery",
                        to="accounts.premiumauditlog",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.premiumsubscription"),
                ),
            ],
            options={
                "verbose_name": "課金メール配送",
                "verbose_name_plural": "課金メール配送",
                "indexes": [models.Index(fields=["status", "next_attempt_at"], name="billing_mail_due_idx")],
            },
        ),
    ]
