# Generated by Django 5.2.15 on 2026-07-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("source", models.CharField(choices=[("line", "LINE")], default="line", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新規"),
                            ("investigating", "調査中"),
                            ("waiting", "利用者回答待ち"),
                            ("resolved", "対応済み"),
                            ("closed", "終了"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("line_user_id", models.CharField(db_index=True, max_length=255)),
                ("notification_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("text", "テキスト"), ("image", "画像"), ("other", "その他")], max_length=16
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("line_message_id", models.CharField(max_length=255, unique=True)),
                ("attachment", models.FileField(blank=True, upload_to="support/line/%Y/%m/%d/")),
                ("raw_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="support.supportticket"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="LineWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "受信済み"),
                            ("processed", "処理済み"),
                            ("ignored", "対象外"),
                            ("failed", "失敗"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("last_error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_events",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ("-received_at",),
            },
        ),
    ]
