from datetime import timedelta

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.utils import timezone

from accounts.models import PremiumAccessCode, PremiumSubscription


class Command(BaseCommand):
    help = 'ローカル確認用の課金テストユーザーとプレミアムコードを作成します。'

    def add_arguments(self, parser):
        parser.add_argument(
            '--password',
            default='password123',
            help='作成または更新するテストユーザーのパスワード。',
        )
        parser.add_argument(
            '--code-expires-in-days',
            type=int,
            default=30,
            help='発行する運営コードの有効期限日数。0以下なら無期限。',
        )
        parser.add_argument(
            '--include-admin',
            action='store_true',
            help='管理画面確認用のスーパーユーザー billing-admin も作成します。',
        )

    def handle(self, *args, **options):
        password = options['password']
        User = get_user_model()

        free_user = self._upsert_user(
            User,
            username='billing-free',
            email='billing-free@example.com',
            password=password,
            is_premium=False,
        )
        premium_user = self._upsert_user(
            User,
            username='billing-premium',
            email='billing-premium@example.com',
            password=password,
            is_premium=True,
        )
        PremiumSubscription.objects.update_or_create(
            user=premium_user,
            defaults={
                'subscription_status': 'promo',
                'access_source': 'manual',
                'premium_expires_at': None,
                'revoked_at': None,
                'revoked_reason': '',
            },
        )
        code_user = self._upsert_user(
            User,
            username='billing-code',
            email='billing-code@example.com',
            password=password,
            is_premium=False,
        )

        expires_at = None
        if options['code_expires_in_days'] > 0:
            expires_at = timezone.now() + timedelta(days=options['code_expires_in_days'])
        access_code, raw_code = PremiumAccessCode.issue(
            label='local-demo',
            max_uses=10,
            expires_at=expires_at,
            note='Local billing verification code generated by setup_billing_local.',
        )

        self.stdout.write(self.style.SUCCESS('Local billing users are ready.'))
        self.stdout.write(f'- free user: {free_user.username} / {password}')
        self.stdout.write(f'- premium user: {premium_user.username} / {password}')
        self.stdout.write(f'- code user: {code_user.username} / {password}')
        self.stdout.write(f'- premium code: {raw_code}')
        self.stdout.write(f'- premium code id: {access_code.pk}')
        self.stdout.write(
            '- premium code expires at: '
            f'{access_code.expires_at.isoformat() if access_code.expires_at else "never"}'
        )
        self.stdout.write('Stripe checkout configuration:')
        self.stdout.write(
            '- monthly price id: '
            f'{getattr(settings, "STRIPE_PREMIUM_PRICE_ID", "") or "not configured"}'
        )
        self.stdout.write(
            '- yearly price id: '
            f'{getattr(settings, "STRIPE_PREMIUM_YEARLY_PRICE_ID", "") or "not configured"}'
        )
        self.stdout.write(
            '- expected currency: '
            f'{getattr(settings, "STRIPE_PREMIUM_EXPECTED_CURRENCY", "") or "not configured"}'
        )
        self.stdout.write(
            '- expected monthly unit amount: '
            f'{getattr(settings, "STRIPE_PREMIUM_MONTHLY_EXPECTED_UNIT_AMOUNT", "") or "not configured"}'
        )
        self.stdout.write(
            '- expected yearly unit amount: '
            f'{getattr(settings, "STRIPE_PREMIUM_YEARLY_EXPECTED_UNIT_AMOUNT", "") or "not configured"}'
        )
        self.stdout.write(
            '- checkout enabled: '
            f'{str(getattr(settings, "STRIPE_CHECKOUT_ENABLED", False)).lower()}'
        )
        self.stdout.write('- development env file: .env.development')
        self.stdout.write(
            '- create test Prices: python manage.py create_stripe_development_prices'
        )
        self.stdout.write('- verify settings: python manage.py billing_preflight')
        self.stdout.write('- monthly checkout button appears when STRIPE_PREMIUM_PRICE_ID is set')
        self.stdout.write('- yearly checkout button appears when STRIPE_PREMIUM_YEARLY_PRICE_ID is set')
        self.stdout.write('Local verification URLs:')
        self.stdout.write('- billing: http://127.0.0.1:8000/accounts/billing/')
        self.stdout.write('- premium features: http://127.0.0.1:8000/premium/')
        self.stdout.write('- commercial disclosure: http://127.0.0.1:8000/commercial-disclosure/')
        self.stdout.write('- admin: http://127.0.0.1:8000/admin/')

        if options['include_admin']:
            admin_user = self._upsert_user(
                User,
                username='billing-admin',
                email='billing-admin@example.com',
                password=password,
                is_premium=True,
                is_staff=True,
                is_superuser=True,
            )
            self.stdout.write(f'- admin user: {admin_user.username} / {password}')

    def _upsert_user(
        self,
        User,
        *,
        username,
        email,
        password,
        is_premium,
        is_staff=False,
        is_superuser=False,
    ):
        user, _ = User.objects.get_or_create(username=username, defaults={'email': email})
        user.email = email
        user.is_premium = is_premium
        user.is_staff = is_staff
        user.is_superuser = is_superuser
        user.set_password(password)
        user.save(update_fields=[
            'email',
            'is_premium',
            'is_staff',
            'is_superuser',
            'password',
        ])
        return user


