# Generated by Django 5.2.3 on 2025-06-14 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gm', 'GM'), ('player', 'PL')], default='player', max_length=10)),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('character_sheet_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TRPGSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('youtube_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('planned', '予定'), ('ongoing', '進行中'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='planned', max_length=10)),
                ('visibility', models.CharField(choices=[('private', 'プライベート'), ('group', 'グループ内'), ('public', '公開')], default='group', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='セッション時間（分）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gm_sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.group')),
                ('participants', models.ManyToManyField(related_name='sessions', through='schedules.SessionParticipant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.trpgsession'),
        ),
        migrations.CreateModel(
            name='HandoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_secret', models.BooleanField(default=True, help_text='秘匿ハンドアウトかどうか')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='schedules.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handouts', to='schedules.trpgsession')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
