# Generated by Django 5.2.3 on 2025-06-18 13:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handout_notifications_enabled', models.BooleanField(default=True, help_text='ハンドアウト通知を有効にする')),
                ('email_notifications_enabled', models.BooleanField(default=False, help_text='メール通知を有効にする')),
                ('browser_notifications_enabled', models.BooleanField(default=True, help_text='ブラウザ通知を有効にする')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandoutNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handout_id', models.PositiveIntegerField(help_text='対象ハンドアウトのID')),
                ('notification_type', models.CharField(choices=[('handout_created', 'ハンドアウト作成'), ('handout_published', 'ハンドアウト公開'), ('handout_updated', 'ハンドアウト更新')], max_length=20)),
                ('message', models.TextField(help_text='通知メッセージ')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handout_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_handout_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='schedules_h_recipie_c78fb5_idx'), models.Index(fields=['handout_id'], name='schedules_h_handout_9cc3a6_idx')],
            },
        ),
    ]
