# Generated by Django 5.2.3 on 2025-06-18 13:17

import django.db.models.deletion
import django.utils.timezone
import schedules.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_usernotificationpreferences_handoutnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoutAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=schedules.models.handout_attachment_upload_path)),
                ('original_filename', models.CharField(help_text='元のファイル名', max_length=255)),
                ('file_type', models.CharField(choices=[('image', '画像'), ('pdf', 'PDF'), ('audio', '音声'), ('video', '動画'), ('document', '文書')], max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='ファイルサイズ（バイト）')),
                ('content_type', models.CharField(help_text='MIMEタイプ', max_length=100)),
                ('description', models.TextField(blank=True, help_text='添付ファイルの説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='schedules.handoutinfo')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handout', '-created_at'], name='schedules_h_handout_565e3b_idx'), models.Index(fields=['file_type'], name='schedules_h_file_ty_7dd22c_idx'), models.Index(fields=['uploaded_by'], name='schedules_h_uploade_488b81_idx')],
            },
        ),
    ]
