# Generated by Django 5.2.3 on 2025-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_handoutattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoutnotification',
            name='metadata',
            field=models.JSONField(blank=True, help_text='追加メタデータ', null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='session_notifications_enabled',
            field=models.BooleanField(default=True, help_text='セッション通知を有効にする'),
        ),
        migrations.AlterField(
            model_name='handoutnotification',
            name='handout_id',
            field=models.PositiveIntegerField(help_text='対象ハンドアウトのID（セッション通知の場合は0）'),
        ),
        migrations.AlterField(
            model_name='handoutnotification',
            name='notification_type',
            field=models.CharField(choices=[('handout_created', 'ハンドアウト作成'), ('handout_published', 'ハンドアウト公開'), ('handout_updated', 'ハンドアウト更新'), ('session_invitation', 'セッション招待'), ('schedule_change', 'スケジュール変更'), ('session_cancelled', 'セッションキャンセル'), ('session_reminder', 'セッションリマインダー')], max_length=30),
        ),
    ]
