# Generated by Django 5.2.3 on 2025-06-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_characterimage_image'),
        ('schedules', '0004_handoutnotification_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handoutinfo',
            options={'ordering': ['handout_number', 'title']},
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
        migrations.AddField(
            model_name='handoutinfo',
            name='assigned_player_slot',
            field=models.IntegerField(blank=True, choices=[(1, 'プレイヤー1'), (2, 'プレイヤー2'), (3, 'プレイヤー3'), (4, 'プレイヤー4')], help_text='割り当てられたプレイヤー枠', null=True),
        ),
        migrations.AddField(
            model_name='handoutinfo',
            name='handout_number',
            field=models.IntegerField(blank=True, choices=[(1, 'HO1'), (2, 'HO2'), (3, 'HO3'), (4, 'HO4')], help_text='ハンドアウト番号（HO1-HO4）', null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='character_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participations', to='accounts.charactersheet'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='player_slot',
            field=models.IntegerField(blank=True, choices=[(1, 'プレイヤー1'), (2, 'プレイヤー2'), (3, 'プレイヤー3'), (4, 'プレイヤー4')], help_text='プレイヤー枠番号（1-4）', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='handoutinfo',
            unique_together={('session', 'handout_number')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'player_slot'), ('session', 'user')},
        ),
    ]
