# Generated by Django 5.2.3 on 2025-07-21 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_charactersheet_recommended_skills'),
        ('schedules', '0007_sessionyoutubelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('gm_private', 'GMプライベート'), ('public_summary', '公開サマリー'), ('player_note', 'プレイヤーノート'), ('npc_memo', 'NPCメモ'), ('handover', '引き継ぎ事項')], default='player_note', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schedules.trpgsession')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at', '-created_at'],
                'indexes': [
                    models.Index(fields=['session', 'note_type'], name='schedules_s_session_b5512b_idx'),
                    models.Index(fields=['author', '-created_at'], name='schedules_s_author_b9a0b3_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(default='general', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('related_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='accounts.charactersheet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='schedules.trpgsession')),
            ],
            options={
                'ordering': ['timestamp', 'created_at'],
                'indexes': [
                    models.Index(fields=['session', 'timestamp'], name='schedules_s_session_07710f_idx'),
                    models.Index(fields=['created_by', '-created_at'], name='schedules_s_created_94f6a5_idx'),
                ],
            },
        ),
    ]
