# Generated by Django 4.2.27 on 2025-12-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_trpgsession_scenario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='schedules_s_session_628b50_idx',
            old_name='schedules_s_session_07710f_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionlog',
            new_name='schedules_s_created_a09bf1_idx',
            old_name='schedules_s_created_94f6a5_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionnote',
            new_name='schedules_s_session_5f99db_idx',
            old_name='schedules_s_session_b5512b_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionnote',
            new_name='schedules_s_author__9d2f97_idx',
            old_name='schedules_s_author_b9a0b3_idx',
        ),
    ]
