# Generated by Django 4.2.27 on 2026-01-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0013_group_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '保留'), ('accepted', '受諾'), ('declined', '辞退'), ('expired', '期限切れ')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='招待メッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_session_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_session_invitations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='schedules.trpgsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('session', 'invitee')},
            },
        ),
    ]
