# Generated by Django 4.2.27 on 2026-01-12 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0016_trpgsession_share_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('content', models.TextField(blank=True, default='')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionOccurrenceParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.sessionoccurrence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='session_occurrences', through='schedules.SessionOccurrenceParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionoccurrence',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='schedules.trpgsession'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrenceparticipant',
            index=models.Index(fields=['occurrence', 'user'], name='schedules_s_occurre_ac44f8_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrenceparticipant',
            index=models.Index(fields=['user', 'occurrence'], name='schedules_s_user_id_fcb1ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionoccurrenceparticipant',
            unique_together={('occurrence', 'user')},
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['session', 'start_at'], name='schedules_s_session_40302e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionoccurrence',
            index=models.Index(fields=['session', 'is_primary'], name='schedules_s_session_e90b71_idx'),
        ),
    ]
