# Generated by Django 5.2.3 on 2026-01-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0024_trpgsession_coc_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='guest_name',
            field=models.CharField(blank=True, default='', help_text='ゲスト参加者名（ログインなし参加者）', max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(
                check=models.Q(user__isnull=False) | ~models.Q(guest_name=''),
                name='sessionparticipant_user_or_guest_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(
                check=~models.Q(role='gm') | models.Q(user__isnull=False),
                name='sessionparticipant_gm_requires_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(
                check=models.Q(character_sheet__isnull=True) | models.Q(user__isnull=False),
                name='sessionparticipant_character_sheet_requires_user',
            ),
        ),
    ]
