# Generated by Django 4.2.27 on 2026-01-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_customuser_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scenarios', '0005_scenarioimage'),
        ('schedules', '0027_remove_datepollvote_unique_poll_vote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='セッション時間（分）')),
                ('visibility', models.CharField(choices=[('private', 'プライベート'), ('group', 'グループ内'), ('public', '公開')], default='group', max_length=10)),
                ('coc_edition', models.CharField(choices=[('6th', 'CoC 6版'), ('7th', 'CoC 7版')], default='6th', help_text='クトゥルフ神話TRPGの版（探索者作成で使用）', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_templates', to='accounts.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_templates', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['owner', 'name'], name='schedules_s_owner_i_5c81a0_idx')],
            },
        ),
    ]
