# Generated by Django 4.2.27 on 2026-01-25 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_customuser_is_premium'),
        ('schedules', '0028_sessiontemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('special_rewards', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_growth_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_reward', to='accounts.growthrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_rewards', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='schedules.sessionparticipant')),
            ],
            options={
                'ordering': ['participant_id'],
                'indexes': [models.Index(fields=['participant'], name='schedules_s_partici_138415_idx')],
            },
        ),
    ]
