# Generated by Django 4.2.27 on 2026-04-18 22:32

import os
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def session_template_image_upload_path(instance, filename):
    _, ext = os.path.splitext(filename)
    safe_filename = f"{django.utils.timezone.now().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:8]}{ext}"
    template_id = instance.session_template_id or "tmp"
    return f"session_template_images/{template_id}/{safe_filename}"


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0029_sessionreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontemplate",
            name="copy_handouts_to_session",
            field=models.BooleanField(
                default=False, help_text="テンプレートのハンドアウト設定を新規セッションへ引き継ぐ"
            ),
        ),
        migrations.CreateModel(
            name="SessionTemplateImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=session_template_image_upload_path)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_templates",
                        to="schedules.sessiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "indexes": [models.Index(fields=["session_template", "order"], name="schedules_s_session_eb57f5_idx")],
            },
        ),
        migrations.CreateModel(
            name="SessionTemplateHandout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("recommended_skills", models.TextField(blank=True, default="")),
                ("is_secret", models.BooleanField(default=True)),
                (
                    "handout_number",
                    models.IntegerField(
                        blank=True, choices=[(1, "HO1"), (2, "HO2"), (3, "HO3"), (4, "HO4")], null=True
                    ),
                ),
                (
                    "assigned_player_slot",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "プレイヤー1"), (2, "プレイヤー2"), (3, "プレイヤー3"), (4, "プレイヤー4")],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handout_templates",
                        to="schedules.sessiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["handout_number", "id"],
                "unique_together": {("session_template", "handout_number")},
            },
        ),
    ]
