# Generated by Django 4.2.27 on 2026-06-11 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0033_googleintegration_googlecalendarsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guest_invitations', to=settings.AUTH_USER_MODEL)),
                ('participant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_invitation', to='schedules.sessionparticipant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_invitations', to='schedules.trpgsession')),
            ],
        ),
        migrations.CreateModel(
            name='GuestClaimAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('character_sheet_url', models.URLField(blank=True)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_claim_audits', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_audits', to='schedules.guestinvitation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_audits', to='schedules.sessionparticipant')),
            ],
        ),
    ]
