# Generated by Codex on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0034_guestinvitation_guestclaimaudit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SessionLog",
        ),
        migrations.DeleteModel(
            name="SessionNote",
        ),
    ]
