# Generated by Django 4.2.27 on 2026-06-18 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0035_remove_sessionnote_sessionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('source', models.CharField(default='cao_csv', max_length=255)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
