# Generated by Django 5.2.15 on 2026-06-27 01:29

from django.db import migrations


def delete_session_template_image_files(apps, schema_editor):
    SessionTemplateImage = apps.get_model("schedules", "SessionTemplateImage")
    for image in SessionTemplateImage.objects.exclude(image="").iterator():
        field_file = image.image
        image_name = getattr(field_file, "name", None)
        if not image_name:
            continue
        try:
            storage = field_file.storage
            if storage.exists(image_name):
                storage.delete(image_name)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0040_alter_handoutinfo_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            delete_session_template_image_files,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="SessionTemplateImage",
        ),
        migrations.DeleteModel(
            name="SessionTemplateHandout",
        ),
        migrations.DeleteModel(
            name="SessionTemplate",
        ),
    ]
