# Generated by Django 5.2.15 on 2026-06-27 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0043_participantidentity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionparticipant',
            name='sessionparticipant_gm_requires_user',
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'gm'), _negated=True), ('user__isnull', False), ('participant_identity__isnull', False), _connector='OR'), name='sessionparticipant_gm_requires_user'),
        ),
    ]
