# Generated by Django 5.2.15 on 2026-07-08 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0049_participantidentity_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('review_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='schedules.sessionparticipant')),
                ('participant_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='schedules.participantidentity')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_claim_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_participant_claim_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='part_claim_status_created_idx'), models.Index(fields=['requested_by', 'status'], name='part_claim_requester_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('participant__isnull', False), ('participant_identity__isnull', False), _connector='OR'), name='participant_claim_has_target'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('participant', 'requested_by'), name='uniq_pending_participant_claim'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('participant_identity', 'requested_by'), name='uniq_pending_identity_claim')],
            },
        ),
    ]
