# Generated by Django 5.2.3 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedules", "0051_unify_session_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionparticipant",
            name="character_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="session_participations",
                to="accounts.charactersheet",
            ),
        ),
    ]
