# Generated by Django 5.2.15 on 2026-07-15 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_minimize_character_sheet_registry"),
        ("schedules", "0052_delete_session_participant_with_character_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionparticipant",
            name="character_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_participations",
                to="accounts.charactersheet",
            ),
        ),
    ]
