# Generated by Django 5.2.15 on 2026-07-25 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0053_unlink_deleted_character_sheets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionRecruitmentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_digest", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("use_count", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_session_recruitment_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_links",
                        to="schedules.trpgsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SessionRecruitmentLinkUse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "joined_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_recruitment_link_uses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_link_uses",
                        to="schedules.sessionparticipant",
                    ),
                ),
                (
                    "recruitment_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uses",
                        to="schedules.sessionrecruitmentlink",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sessionrecruitmentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_uses__gte", 1), ("max_uses__lte", 1000)),
                name="recruitment_link_max_uses_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionrecruitmentlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("use_count__lte", models.F("max_uses"))), name="recruitment_link_use_count_lte_max"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionrecruitmentlinkuse",
            constraint=models.UniqueConstraint(
                fields=("recruitment_link", "joined_by"), name="unique_recruitment_link_joined_by"
            ),
        ),
    ]
